apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  labels:
    app: {{ .Chart.Name }}
data:
  config.yaml: |
    logging:
      level: {{ .Values.logging.level }}
    mlflow:
      enabled: {{ .Values.mlflow.enabled }}
      trackingUri: {{ .Values.mlflow.trackingUri }}
      experimentName: {{ .Values.mlflow.experimentName }}
