apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  labels:
    app: {{ .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Chart.Name }}
  ports:
    - name: fastapi
      port: {{ .Values.service.ports.fastapi }}
      targetPort: {{ .Values.service.ports.fastapi }}
    - name: streamlit
      port: {{ .Values.service.ports.streamlit }}
      targetPort: {{ .Values.service.ports.streamlit }}
